name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        -
            name: Check out repository code
            uses: actions/checkout@v3

        -
            name: Deploy with opentofu
            uses: opentofu/setup-opentofu@v1
            with:
              tofu_version: 1.6.2



        - run: tofu init

        - run: wget ${{ secrets.URL_ADDRESS }}
        - run: tofu plan --var "token=${{ secrets.TOKEN }}" --var "pvt_key=${{ secrets.SSH_KEY }} " -out deploy

        - run: tofu apply "deploy"

        - uses: BetaHuhn/do-spaces-action@v2
          with:
            access_key: ${{ secrets.ACCESS_KEY}}
            secret_key: ${{ secrets.SECRET_KEY }}
            space_name: ${{ secrets.SPACE_NAME }}
            space_region: ${{ secrets.SPACE_REGION }}
            source: terraform.tfstate
            versioning: true

